Add logging
emranprojects/semangit pull request #15
Opened 2023-01-01 14:30 UTC by Adibov

Add logging to the source code using the _logrus_ library.

2023-01-01 15:49 UTC, Adibov commented
Also [in this line](https://github.com/divar-ir/semangit/blob/5cee625a23a808ed441a608a4a3dfb7d07dac4ad/internal/models/versionanalyzers/helm_version_analyzer.go#L51) I needed to print variables but wasn't sure that it should be on the final release. So what do you think about printing these values in debug mode also?

2023-01-02 08:05 UTC, emranbm approved these changes, later dismissed

2023-01-02 08:05 UTC, emranbm commented on cmd/root.go
> +		"logger-level",
```suggestion
		"log-level",
```

2023-01-02 08:05 UTC, emranbm commented on cmd/run.go
> +	logrus.Debug("Computed config:\n", utils.InterfaceToString(conf))
```suggestion
	logrus.Debug("Loaded config:\n", utils.InterfaceToString(conf))
```

2023-01-02 08:05 UTC, emranbm commented on cmd/run.go
> +		logrus.Debug("Successfully checked out on ", conf.NewRevision)
```suggestion
		logrus.Debug("Successfully checked out the new revision: ", conf.NewRevision)
```

2023-01-02 08:05 UTC, emranbm commented on cmd/run.go
> +	logrus.Debug("Successfully checked out on ", conf.OldRevision)
```suggestion
	logrus.Debug("Successfully checked out the old revision: ", conf.OldRevision)
```

2023-01-02 08:05 UTC, emranbm commented on cmd/run.go
> +	logrus.Debug("New Version: ", newVersion)
```suggestion
	logrus.Info("New Version: ", newVersion)
```

2023-01-02 08:05 UTC, emranbm commented on cmd/run.go
> +	logrus.Debug("Old Version: ", oldVersion)
```suggestion
	logrus.Info("Old Version: ", oldVersion)
```

2023-01-02 08:05 UTC, emranbm commented on cmd/run.go
> +	logrus.Debug("Needs Update: ", needsUpdate)
```suggestion
	logrus.Debug("Does the version need update: ", needsUpdate)
```

2023-01-02 08:05 UTC, emranbm commented on internal/config/config.go
> +	if loggerLevelFlag != nil {
Can it be `nil`?!

2023-01-02 08:05 UTC, emranbm commented on cmd/root.go
> +		"Level of the logger, options are (trace, debug, info, warn, error, fatal, panic)",
```suggestion
		"Verbosity of Semangit logs. Options: trace, debug, info, warn, error, fatal, panic",
```

2023-01-02 08:05 UTC, emranbm commented on internal/models/versionanalyzers/helm_version_analyzer.go
> +		logrus.Debug("Values Path: ", valuesPath)
Please move these out of loop.

2023-01-02 08:05 UTC, emranbm commented on internal/models/versionanalyzers/helm_version_analyzer.go
> +		logrus.Debug("Abs Path: ", absPath)
```suggestion
		logrus.Debug("Changed file: ", absPath)
```

2023-01-02 12:16 UTC, Adibov commented on internal/config/config.go
> +	if loggerLevelFlag != nil {
Actually, some tests failed because of not registering this flag, So I added the nil checkup.

2023-01-02 12:50 UTC, emranbm requested changes

2023-01-02 12:50 UTC, emranbm commented on internal/config/config.go
> +	loggerLevelFlag := cmd.Flags().Lookup("log-level")
```suggestion
	logLevelFlag := cmd.Flags().Lookup("log-level")
```
LOL :)

2023-01-02 12:50 UTC, emranbm commented on internal/config/config_test.go
> +	s.Equal(logrus.GetLevel(), logrus.PanicLevel)
Duplicate test logic. Please make it a private helper method.

2023-01-02 16:51 UTC, emranbm approved these changes, later dismissed

2023-01-02 16:54 UTC, emranbm approved these changes
Great!

2023-01-02 16:54 UTC, merged