Add Cobra and Viper
emranprojects/semangit pull request #3
Opened 2022-11-05 11:47 UTC by Adibov

Use _Cobra_ for cli commands and _Viper_ for reading configs.

2022-11-06 15:34 UTC, emranbm requested changes

2022-11-06 15:34 UTC, emranbm commented on cmd/root.go
> +Copyright © 2022 NAME HERE <EMAIL ADDRESS>
Please remove this.

2022-11-06 15:34 UTC, emranbm commented on cmd/root.go
> +	Long:  `With semangit you can check your versions!`, // TODO: complete this description
```suggestion
	Long:  `A simple tool to force version update in CI.`,
```

2022-11-06 15:34 UTC, emranbm commented on cmd/root.go
> +	Use:   "serve",
serve? What's being served?  
What about `run`? or s.th. like that.

2022-11-06 15:34 UTC, emranbm commented on cmd/root.go
> +		if err := serveSemanGit(cmd, args); err != nil {
*Semangit* is a single name.
```suggestion
		if err := serveSemangit(cmd, args); err != nil {
```

2022-11-06 15:34 UTC, emranbm commented on cmd/root.go
> +	utils.PanicError(versionanalyzer.RegisterVersionAnalyzer(helm.New()))
Based on our discussion, it's better to initialize explicitly in the main and keep the registration on the analyzer itself.

2022-11-06 15:34 UTC, emranbm commented on cmd/root.go
> +		"Specify repository address",
Is it the *error message* or *help*? If it's a help text, seems better to have a declarative accent:  
```suggestion
		"The repository directory",
```

2022-11-06 15:34 UTC, emranbm commented on internal/config/config.go
> +	ActiveVersionAnalyzerName string                     `json:"active_version_analyzer_name,omitempty""`
As we have used **Current** in `GetCurrentVersionAnalyzerArgumentValues`, for the sake of consistency I recommend `CurrentVersionAnalyzerName` as well.

2022-11-06 15:34 UTC, emranbm commented on internal/plugins/versionanalyzer/repository.go
`versionAnalyzer` directory next to `base` and `helm` is confusing. I think removing the `cobra` init function will solve the cyclic import problem that probably is the root cause of this directory structure change.

2022-11-07 07:59 UTC, Adibov commented on cmd/root.go
> +	Use:   "serve",
How about `analyze`?

2022-11-07 15:15 UTC, emranbm commented on cmd/serve.go
> +package cmd
Please also rename this file name.

2022-11-07 15:20 UTC, emranbm commented on cmd/root.go
> +		"The source revision",
```suggestion
		"The source git revision",
```

2022-11-07 15:20 UTC, emranbm commented on cmd/root.go
> +		"The destination revision",
```suggestion
		"The destination git revision",
```

2022-11-07 15:29 UTC, emranbm commented on internal/versionanalyzers/config.go
> +type Config struct {
Based on our discussion, please remove `Config`

2022-11-07 16:02 UTC, emranbm approved these changes
Thanks!

2022-11-07 16:02 UTC, merged